package asedinfo.com.modelo.competencia;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * wp_integrante generated by hbm2java
 */
@Entity
@Table(name = "wp_integrante")
public class Integrante implements java.io.Serializable {
	private static final long serialVersionUID = -8622196233866959952L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;

	@Column(name = "nombre")
	private String nombre;

	@Column(name = "estado", nullable = false, length = 1)
	private String estado;
	
	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "cod_participante", nullable = false)
	private Participante participante;

	@Transient
	private Long codParticipante;
	@Transient
	private String nombreParticipante;
	@Transient
	private String nombreIntegrante;
	@Transient
	private String correo;

	public Integrante() {
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Participante getParticipante() {
		return participante;
	}

	public void setParticipante(Participante participante) {
		this.participante = participante;
	}

	public Long getCodParticipante() {
		if (this.participante != null) {
			codParticipante = this.participante.getCodigo();
		}
		return codParticipante;
	}

	public void setCodParticipante(Long codParticipante) {
		this.codParticipante = codParticipante;
	}

	public String getNombreParticipante() {
		if (this.participante != null) {
			nombreParticipante = this.participante.getFirstName();
		}
		return nombreParticipante;
	}

	public void setNombreParticipante(String nombreParticipante) {
		this.nombreParticipante = nombreParticipante;
	}

	public String getNombreIntegrante() {
		if (this.participante != null) {
			nombreIntegrante = this.participante.getLastName();
		}
		return nombreIntegrante;
	}

	public void setNombreIntegrante(String nombreIntegrante) {
		this.nombreIntegrante = nombreIntegrante;
	}

	public String getCorreo() {
		if (this.participante != null) {
			correo = this.participante.getEmail();
		}
		return correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}
}
