package asedinfo.com.modelo.competencia;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * wp_integrante generated by hbm2java
 */
@Entity
@Table(name = "wp_participante_seguimiento")
public class ParticipanteSeguimiento implements java.io.Serializable {
	private static final long serialVersionUID = -8622196233866959952L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;

	@Column(name = "estado", nullable = false, length = 1)
	private String estado;

	@Column(name = "cod_participante")
	private Long codParticipante;

	@Column(name = "cod_seguimiento")
	private Long codSeguimiento;

	public ParticipanteSeguimiento() {
	}

	public Long getCodigo() {
		return codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Long getCodParticipante() {
		return codParticipante;
	}

	public void setCodParticipante(Long codParticipante) {
		this.codParticipante = codParticipante;
	}

	public Long getCodSeguimiento() {
		return codSeguimiento;
	}

	public void setCodSeguimiento(Long codSeguimiento) {
		this.codSeguimiento = codSeguimiento;
	}
}
