package asedinfo.com.modelo.competencia;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import com.fasterxml.jackson.annotation.JsonIgnore;

import asedinfo.com.modelo.catalogo.Instancia;
import asedinfo.com.modelo.catalogo.ModeloPuntaje;
import asedinfo.com.modelo.catalogo.Subcategoria;

/**
 * wp_puntaje generated by hbm2java
 */
@Entity
@Table(name = "wp_puntaje")
public class Puntaje implements java.io.Serializable {
	private static final long serialVersionUID = -8622196233866959952L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;
	
	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "cod_modelo_puntaje", nullable = false)
	private ModeloPuntaje modeloPuntaje;
	
	@Transient
	private Long codModeloPuntaje;
	@Transient
	private String desModeloPuntaje;
	
	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "cod_instancia", nullable = false)
	private Instancia instancia;
	
	@Transient
	private Long codInstancia;
	@Transient
	private String desInstancia;
	
	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "cod_participante", nullable = false)
	private Participante participante;
	
	@Transient
	private Long codParticipante;
	@Transient
	private String nombreParticipante;
	
	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "cod_subcategoria", nullable = false)
	private Subcategoria subcategoria;
	@Transient
	private Long codSubcategoria;
	@Transient
	private String desSubcategoria;
	@Transient
	private Long codCategoria;
	@Transient
	private String desCategoria;

	@Transient
	private String pathImagenTrofeo;
	
	@Column(name = "puntaje")
	private Float puntaje;

	@Column(name = "estado", nullable = false, length = 1)
	private String estado;
	/*
	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "cod_usuario_juez", nullable = false)
	private Usuario usuarioJuez;
	@Transient
	*/
	@Column(name = "cod_usuario_juez")
	private Long codUsuarioJuez;

	public Puntaje() {
	}

	public Long getCodigo() {
		return codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public ModeloPuntaje getModeloPuntaje() {
		return modeloPuntaje;
	}

	public void setModeloPuntaje(ModeloPuntaje modeloPuntaje) {
		this.modeloPuntaje = modeloPuntaje;
	}

	public Long getCodModeloPuntaje() {
		if (this.modeloPuntaje != null) {
			codModeloPuntaje = this.modeloPuntaje.getCodigo();
		}
		return codModeloPuntaje;
	}

	public void setCodModeloPuntaje(Long codModeloPuntaje) {
		this.codModeloPuntaje = codModeloPuntaje;
	}

	public String getDesModeloPuntaje() {
		if (this.modeloPuntaje != null) {
			desModeloPuntaje = this.modeloPuntaje.getDenominacion();
		}
		return desModeloPuntaje;
	}

	public void setDesModeloPuntaje(String desModeloPuntaje) {
		this.desModeloPuntaje = desModeloPuntaje;
	}

	public Instancia getInstancia() {
		return instancia;
	}

	public void setInstancia(Instancia instancia) {
		this.instancia = instancia;
	}

	public Long getCodInstancia() {
		if (this.instancia != null) {
			codInstancia = this.instancia.getCodigo();
		}
		return codInstancia;
	}

	public void setCodInstancia(Long codInstancia) {
		this.codInstancia = codInstancia;
	}

	public String getDesInstancia() {
		if (this.instancia != null) {
			desInstancia = this.instancia.getDenominacion();
		}
		return desInstancia;
	}

	public void setDesInstancia(String desInstancia) {
		this.desInstancia = desInstancia;
	}

	public Participante getParticipante() {
		return participante;
	}

	public void setParticipante(Participante participante) {
		this.participante = participante;
	}

	public Long getCodParticipante() {
		if (this.participante != null) {
			codParticipante = this.participante.getCodigo();
		}
		return codParticipante;
	}

	public void setCodParticipante(Long codParticipante) {
		this.codParticipante = codParticipante;
	}

	public String getNombreParticipante() {
		if (this.participante != null) {
			nombreParticipante = this.participante.getFirstName() + " " + this.participante.getLastName();
		}
		return nombreParticipante;
	}

	public void setNombreParticipante(String nombreParticipante) {
		this.nombreParticipante = nombreParticipante;
	}

	public Subcategoria getSubcategoria() {
		return subcategoria;
	}

	public void setSubcategoria(Subcategoria subcategoria) {
		this.subcategoria = subcategoria;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Float getPuntaje() {
		return puntaje;
	}

	public void setPuntaje(Float puntaje) {
		this.puntaje = puntaje;
	}

	public Long getCodSubcategoria() {
		if (this.subcategoria != null) {
			codSubcategoria = this.subcategoria.getCodigo();
		}
		return codSubcategoria;
	}

	public void setCodSubcategoria(Long codSubcategoria) {
		this.codSubcategoria = codSubcategoria;
	}

	public String getDesSubcategoria() {
		if (this.subcategoria != null) {
			desSubcategoria = this.subcategoria.getDenominacion();
		}
		return desSubcategoria;
	}

	public void setDesSubcategoria(String desSubcategoria) {
		this.desSubcategoria = desSubcategoria;
	}

	public Long getCodCategoria() {
		if (this.subcategoria != null) {
			codCategoria = this.subcategoria.getCategoria().getCodigo();
		}
		return codCategoria;
	}

	public void setCodCategoria(Long codCategoria) {
		this.codCategoria = codCategoria;
	}

	public String getDesCategoria() {
		if (this.subcategoria != null) {
			desCategoria = this.subcategoria.getCategoria().getDenominacion();
		}
		return desCategoria;
	}

	public void setDesCategoria(String desCategoria) {
		this.desCategoria = desCategoria;
	}
	/*
	public Usuario getUsuarioJuez() {
		return usuarioJuez;
	}

	public void setUsuarioJuez(Usuario usuarioJuez) {
		this.usuarioJuez = usuarioJuez;
	}

	public Long getCodUsuarioJuez() {
		if (this.usuarioJuez != null) {
			codUsuarioJuez = this.usuarioJuez.getCodigo();
		}
		return codUsuarioJuez;
	}
	*/
	public Long getCodUsuarioJuez() {
		return codUsuarioJuez;
	}
	public void setCodUsuarioJuez(Long codUsuarioJuez) {
		this.codUsuarioJuez = codUsuarioJuez;
	}

	public String getPathImagenTrofeo() {
		return pathImagenTrofeo;
	}

	public void setPathImagenTrofeo(String pathImagenTrofeo) {
		this.pathImagenTrofeo = pathImagenTrofeo;
	}
}
