package asedinfo.com.modelo.competencia;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * wp_usuario_modelo_puntaje_op generated by hbm2java
 */
@Entity
@Table(name = "wp_usuario_modelo_puntaje_op")
public class UsuarioModeloPuntajeOp implements java.io.Serializable {
	private static final long serialVersionUID = -8622196233866959952L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;

	@Column(name = "estado", nullable = false, length = 1)
	private String estado;

	@Column(name = "cod_modelo_puntaje")
	private Long codModeloPuntaje;

	@Column(name = "cod_usuario")
	private Long codUsuario;

	public UsuarioModeloPuntajeOp() {
	}

	public Long getCodigo() {
		return codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Long getCodModeloPuntaje() {
		return codModeloPuntaje;
	}

	public void setCodModeloPuntaje(Long codModeloPuntaje) {
		this.codModeloPuntaje = codModeloPuntaje;
	}

	public Long getCodUsuario() {
		return codUsuario;
	}

	public void setCodUsuario(Long codUsuario) {
		this.codUsuario = codUsuario;
	}
}
