package asedinfo.com.modelo.venta;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

import asedinfo.com.modelo.catalogo.Persona;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "ven_cliente")
public class Cliente implements java.io.Serializable {
	private static final long serialVersionUID = -8622196233866959952L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss.SSS", locale = "es-EC", timezone = "America/Lima")
	@Column(name = "fecha_inicio", length = 23)
	private Date fechaInicio;

	@Column(name = "estado", nullable = false, length = 1)
	private String estado;

	@Column(name = "tipo_cliente")
	private String tipoCliente;

	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "cod_persona", nullable = false)
	private Persona persona;

	@Transient
	private Long codPersona;
	@Transient
	private String nombrePersona;
	@Transient
	private String celular;
	@Transient
	private String prefijoTelefonico;
	@Transient
	private String nombres;
	@Transient
	private String apellidos;
	@Transient
	private String correo;
	@Transient
	private String identificacion;
	@Transient
	private String direccion;

	@Transient
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss.SSS", locale = "es-EC", timezone = "America/Lima")
	private Date fechaNacimiento;

	public Cliente() {
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getTipoCliente() {
		return tipoCliente;
	}

	public void setTipoCliente(String tipoCliente) {
		this.tipoCliente = tipoCliente;
	}

	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Long getCodPersona() {
		if (this.persona != null) {
			codPersona = this.persona.getCodigo();
		}

		return codPersona;
	}

	public void setCodPersona(Long codPersona) {
		this.codPersona = codPersona;
	}

	public String getIdentificacion() {
		if (this.persona != null) {
			identificacion = this.persona.getIdentificacion();
		}
		return identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	public String getNombres() {
		if (this.persona != null) {
			nombres = this.persona.getNombres();
		}
		return nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		if (this.persona != null) {
			apellidos = this.persona.getApellidos();
		}
		return apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getCorreo() {
		if (this.persona != null) {
			correo = this.persona.getCorreo();
		}
		return correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getCelular() {
		if (this.persona != null) {
			celular = this.persona.getCelular();
		}
		return celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getNombrePersona() {
		if (this.persona != null) {
			nombrePersona = this.persona.getNombres() + " " + this.persona.getApellidos();
		}
		return nombrePersona;
	}

	public void setNombrePersona(String nombrePersona) {
		this.nombrePersona = nombrePersona;
	}

	public String getDireccion() {
		if (this.persona != null) {
			direccion = this.persona.getDireccion();
		}
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Date getFechaNacimiento() {
		if (this.persona != null) {
			fechaNacimiento = this.persona.getFechaNacimiento();
		}
		return fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getPrefijoTelefonico() {
		if (this.persona != null) {
			prefijoTelefonico = this.persona.getPrefijoTelefonico();
		}
		return prefijoTelefonico;
	}

	public void setPrefijoTelefonico(String prefijoTelefonico) {
		this.prefijoTelefonico = prefijoTelefonico;
	}
}
