package asedinfo.com.modelo.venta;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

import asedinfo.com.modelo.catalogo.Transaccion;

/**
 * ven_cuenta_clave generated by hbm2java
 */
@Entity
@Table(name = "ven_cuenta_clave")
public class CuentaClave implements java.io.Serializable {
	private static final long serialVersionUID = -8622196233866959952L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;

	@Column(name = "cuenta")
	private String cuenta;

	@Column(name = "clave")
	private String clave;

	@Column(name = "estado", nullable = false, length = 1)
	private String estado;
	
	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "cod_transaccion", nullable = false)
	private Transaccion transaccion;

	@Transient
	private Long codTransaccion;
	@Transient
	private String desTransaccion;

	public CuentaClave() {
	}

	public Long getCodigo() {
		return codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public String getCuenta() {
		return cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	public String getClave() {
		return clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Transaccion getTransaccion() {
		return transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	public Long getCodTransaccion() {
		if (transaccion != null) {
			codTransaccion = transaccion.getCodigo();
		}
		return codTransaccion;
	}

	public void setCodTransaccion(Long codTransaccion) {
		this.codTransaccion = codTransaccion;
	}

	public String getDesTransaccion() {
		if (transaccion != null) {
			desTransaccion = transaccion.getDescripcion();
		}
		return desTransaccion;
	}

	public void setDesTransaccion(String desTransaccion) {
		this.desTransaccion = desTransaccion;
	}
}
