package asedinfo.com.modelo.venta;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Table;

/**
 * data_clientes generated by hbm2java
 */
@Table(name = "data_clientes")
public class DataClientes {
	@Column(name = "nombre")
	private String nombre;

	@Column(name = "identificacion")
	private String identificacion;

	@Column(name = "correo")
	private String correo;

	@Column(name = "celular")
	private String celular;

	public DataClientes() {
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getIdentificacion() {
		return identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	public String getCorreo() {
		return correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getCelular() {
		return celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}
}
