package asedinfo.com.modelo.wordpress;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "wp_term_relationships")
public class RelacionProductoWP implements java.io.Serializable {
	private static final long serialVersionUID = -8622196233866959952L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "object_id", unique = true, nullable = false, precision = 10, scale = 0)
	private Long objectId;
	
	@Column(name = "term_taxonomy_id")
	private int termTaxonomyId;
	
	@Column(name = "term_order")
	private int termOrder;

	public RelacionProductoWP() {
	}

	public Long getObjectId() {
		return objectId;
	}

	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	public int getTermTaxonomyId() {
		return termTaxonomyId;
	}

	public void setTermTaxonomyId(int termTaxonomyId) {
		this.termTaxonomyId = termTaxonomyId;
	}

	public int getTermOrder() {
		return termOrder;
	}

	public void setTermOrder(int termOrder) {
		this.termOrder = termOrder;
	}
}
